# Generated by Django 4.2.3 on 2023-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monumentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='year',
            field=models.IntegerField(),
        ),
    ]
